drivers: ata: eswin: Fix section mismatch
This fixes the following section mismatch error:

  WARNING: modpost: drivers/ata/ahci_eswin: section mismatch in reference: \
    ahci_probe+0x38 (section: .text) -> eswin_reset (section: .init.text)
  ERROR: modpost: Section mismatches detected.
  Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.

Fixes: 06d67c26ec75 ("drivers: ata: Add ESWIN sata driver")
Signed-off-by: Emil Renner Berthing <emil.renner.berthing@canonical.com>