Fix img kconfig error.
error: recursive dependency detected!
  symbol DRM is selected by DRM_IMG
  symbol DRM_IMG depends on DRM

Signed-off-by: Jaychand Agrawal <jaychand.agrawal@einfochips.com>